name: cmip6-temperature-demo
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - ipykernel
  - jupyter
  - jupyterlab
  - scipy
  - matplotlib
  - pandas
  - xarray
  - sparse
  - cftime
  - cartopy
  - netcdf4
  - tqdm
  - h5py
  - h5netcdf
  - regionmask
  - xesmf
  - intake
  - intake-xarray
  - zarr
  - xgcm
  - pip
  - intake-esm
